# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 690728edd8352c2a076aec3255263412b83d3cc61ae0f7548b619cd2ae8e7f7595658d3ba4da580848f5af861ec616da6aa38027297403f21a68c88473343201

test:
  secret_key_base: 66cc0e96634b63b323282859cdc6f71d99a4565478bb56087f0c9ae0c3767e9f1fd190a1e460242c5e310177209a34589b328d06c6f5c6b8d93678228ac13150

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
